# Generated by Django 5.0.9 on 2024-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='is_active',
        ),
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
